# Config Swagger  UI
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui-custom.html
        operationsSorter: method

spring:
    # Spring Security
#    security:
#        user:
#            name: admin
#            password: 15012001
#            roles: manager

    # Database Connection properties
    data:
        mongodb:
            uri: mongodb+srv://anhle1512001:Ket0328560055@clustermongochannel.lowln.mongodb.net/internship-new-project?retryWrites=true&w=majority
            database: internship-new-project
            auto-index-creation: true

    # Config properties Mailer
    mail:
        host: smtp.gmail.com
        port: 587
        username: vanhoang1512001@gmail.com
        password: ccsfheygfbxcvzol
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                debug: true

    servlet:
        multipart:
            max-file-size: 2MB
            enabled: true

    # Config properties Redis
    cache:
        type: redis
        redis:
            cache-null-values: false
            time-to-live: 100000
            use-key-prefix: true
    redis:
        database: 0
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:5000}
        password: SVTT_VNPT_IT3


# SECURITY Properties
security:
    jwt:
        token:
            secret-key: JWTSuperSecretKey
            expirationMs: 300000  # 5 minutes
        refreshtoken:
            expirationMs: 604800000 # 7 days

# JWT
com:
    app:
        JWT_AUTH_HEADER: Authorization
        token:
            prefix: Bearer

keystore:
    password: Ket0328560055

# Minio
minio:
    bucket:
        name: minio-uploads-image-news-post
    access:
        key: admin
        secret: password@123
    url: ${MINIO_URL:http://localhost:9000}

prefixOtpCountHit: "otp:hit:"
prefixOtp: "otp:"
prefixApi: "api:"
MAX_REQUEST_VALIDATE_PER_OTP: 5
MAX_REQUEST_SEND_OTP_PER_HOURS: 10
